add dorny reporter

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -16,11 +16,17 @@ jobs:
         run: echo yes | cargo binstall cargo-llvm-cov cargo-nextest
       - name: Run tests and generate coverage
         run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info nextest
-      - name: Publish Test Report
-        uses: mikepenz/action-junit-report@v3
+      - uses: mikepenz/action-junit-report@v3
         if: success() || failure() # always run even if the previous step fails
         with:
+          check_name: mikepenz test report
           report_paths: "**/junit.xml"
+      - uses: dorny/test-reporter@v1
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: dorny test report
+          path: "**/junit.xml"
+          reporter: java-junit
       - name: Upload coverage to Coveralls
         uses: coverallsapp/github-action@v2.0.0
         if: success() || failure() # always run even if the previous step fails
