add mikepenz/action-junit-report@v3

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -16,6 +16,11 @@ jobs:
         run: echo yes | cargo binstall cargo-llvm-cov nextest
       - name: Run tests and generate coverage
         run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info nextest
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: "**/junit.xml"
       - name: Upload coverage to Coveralls
         uses: coverallsapp/github-action@v2.0.0
       - name: Upload coverage to Codecov
